name: OIDC GITACTION TEST DEPLOY

on:
  workflow:_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id_token: write
      contents: read

    steps: 
      - name: checkout repository
        uses: actions/checkout@v3

      - name: configure AWS Cred using OIDC
        uses: aws-actions/configure-aws-credentialv@4
        with:
          role-to-assume: arn:aws:iam::775696080909:role/OIDC-gitaction-demo
          aws-region: us-east-1
      - name: verify AWS access
        run: aws sts get-caller-identity
